# Spark master and workers
master:
  image: georgezhu/spark-notebook
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master-node
  hostname: master-node
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ~/workspace:/home/jovyan/workspace
    - ~/datasource:/home/jovyan/datasource
    - ~/.m2:/home/jovyan/.m2

# unlike distributed datasources like HDFS, datasource folder which is just a file source neededs to be mounted on all nodes
worker1:
  image: georgezhu/spark-notebook
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker-node1
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_DIR: /usr/local/spark/work
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ~/spark-work-dir:/usr/local/spark/work
    - ~/datasource:/home/jovyan/datasource
